---
name: Release

on:
  push:
    branches:
      - main

jobs:
  please:
    name: Please
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          extra-files: README.md
          package-name: scrooge
          pull-request-title-pattern: "chore: release ${version}"
          release-type: elixir
          skip-labeling: true
          TOKEN: ${{ secrets.RELEASE_TOKEN }}
